#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-1.cv62q26aqh6r.ap-northeast-2.rds.amazonaws.com:3306/RankSearch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: gksksla12
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        default_batch_fetch_size: 100
#
#
#  logging:
#    level:
#      org.hibernate.SQL: debug
