#spring:
#  profiles:
#
#      dev: dev
#      test: test
#      prod: prod
#default:
#  string: default property

spring:
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query의 ?에 어떤 값이 들어가는지 추적할 수 있는 설정입니다. TRACE Log에 값을 보여줍니다.

#
#---
#spring:
#  config:
#    activate:
#      on-profile: test
#  #MySQL
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-1.cv62q26aqh6r.ap-northeast-2.rds.amazonaws.com:3306/RankSearchLocal?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: gksksla12
#
#  #JPA
#  jpa:
#    #database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#        highlight_sql: true
#    defer-datasource-initialization: true
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  #MySQL
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-1.cv62q26aqh6r.ap-northeast-2.rds.amazonaws.com:3306/RankSearch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: gksksla12
#
#  #JPA
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
#        format_sql: true
#        show_sql: true
#        highlight_sql: true
#    defer-datasource-initialization: true
